wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725947333.186953
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.11.7
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
